# (C) 2024 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# This image is a armhf version of rpi64-rpios-lite-ci

# set base, copy scripts & out-of-tree resources
FROM sbc:rpi-rpios-lite

# copy 64bit scripts to own snippet directory
COPY images/rpi64-rpios-lite-ci.Dockerfile.d /src/images/rpi64-rpios-lite-ci.Dockerfile.d/
