# (C) 2025,2026 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

FROM sbc:rk1-armbian-vendor AS donor
#FROM sbc:rk1-armbian-current AS donor
FROM sbc:aarch64-alpine-3.24

# keep imported build /vanilla rom with original bmcd and tpi
COPY --from=donor /target/boot                                  /target/boot
COPY --from=donor /target/lib/modules                           /target/lib/modules
COPY --from=donor /target/lib/firmware                          /target/lib/firmware
#COPY --from=donor /target/usr/lib/linux-u-boot-current-turing-rk1  /target/usr/lib/linux-u-boot-current-turing-rk1
COPY --from=donor /target/usr/lib/linux-u-boot-vendor-turing-rk1  /target/usr/lib/linux-u-boot-vendor-turing-rk1

RUN set -e; umask 022; \
  cp -a /target.busybox.static /target/sbin/busybox.static; \
: EO RUN

# recipes
RECIPE alpine/SBC+openrc-init+overlay
# this is needed for Armbian RK1 vendor kernel
RECIPE alpine/SBC+NO_UEVENT_HELPER.hotplug-mdev-patch

RECIPE alpine/ifupdown-ng
RECIPE alpine/ifupdown-ng.update-executors
RECIPE alpine/sshd
RECIPE alpine/chronyd
RECIPE alpine/cloud-init
RECIPE alpine/cleanup.unlink-overloaded-busybox-applets
