# (C) 2024-2025 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

FROM sbc:amd64-EFI-CI-trixie

RECIPE armbian/cross-reduce-upgdate-initrd+grub
RECIPE armbian/kernel-keep-latest
RECIPE armbian/zfs
