#!/usr/bin/python3

# add to /boot/config.txt
#dtparam=i2c1=on
#dtparam=i2c_arm=on

# add to /etc/modules-load.d/i2c.conf
#i2c-dev

# install software
#apt-get install i2c-tools python3-pip python3-smbus2

# add user
#adduser abra i2c

#
# https://www.donskytech.com/raspberry-pi-bme280-weather-station-using-python-and-flask/

import smbus2
import time
import glob
import re
import bme280

DEVICES = ( 0x76, 0x77 )
ID_TABLE = { 88: "bmp280", 96: "bme280" }

if __name__=="__main__":
	# collect data
	result_set = {}
	for i2c_dev_dir in glob.glob('/sys/bus/i2c/devices/i2c-[0-9]*'):
		match = re.search('^/.*/i2c-([0-9]+)$', i2c_dev_dir)
		if match:
			bus_id = int(match.group(1))
			bus = smbus2.SMBus(bus_id)
			print ("# found: i2c_bus = %s" % ( bus_id ))

			for addr in DEVICES:
				try:
					caldata = bme280.load_calibration_params(bus, addr)
				except OSError as ex:
					if ex.errno == 6:
					  continue
					raise ex
					
				sample = bme280.sample(bus, addr, caldata)
				d = { 
					"bus_id": bus_id, 
					"bus": bus, 
					"addr": addr,
					"chip_id": sample.id,
					"pressure": sample.pressure,
					"humidity": sample.humidity,
					"temp": sample.temperature,
				}
				id = "%s-0x%x" % ( bus_id, addr )
				print ("# found: bme280 @ %s" % ( id ))
				result_set[id] = d

	print ('# HELP bme280_temp temperature from readbable BME280 temperatur sensor')
	print ('# TYPE bme280_temp gauge')
	print ('# HELP bme280_pressure pressure from readbable BME280 temperatur sensor')
	print ('# TYPE bme280_pressure gauge')
	print ('# HELP bme280_humidity humidity from readbable BME280 temperatur sensor')
	print ('# TYPE bme280_humidity gauge')
	for k in result_set.keys():
		v = result_set[k]
		print ('bme280_temp{i2c_bus="%s", i2c_addr="%x", id="%s"} %s' % (v["bus_id"], v["addr"], k, v["temp"]))
		print ('bme280_pressure{i2c_bus="%s", i2c_addr="%x", id="%s"} %s' % (v["bus_id"], v["addr"], k, v["pressure"]))
		print ('bme280_humidity{i2c_bus="%s", i2c_addr="%x", id="%s"} %s' % (v["bus_id"], v["addr"], k, v["humidity"]))

# vim: noet ts=2 sw=2
