# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

# This image contains the vanilla os
FROM sbc:turingpi2-buildroot

# set environment - all build containers inherit this
# - ENV - none
CMD \
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  exec env HOME=/root SHELL=/bin/bash chroot /target /bin/bash -l ;\
: # eo CMD
