# (C) 2024-2026 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# this will create a very minimalistic rsyslog container

# see
# # docker image ls
  #    sbc:rsyslog-pure                                                   25f3a2c6647b        4.1MB             0B

# # IRun images/rsyslog-pure.Dockerfile.d/ busybox find / -xdev
  #    /bin
  #    /sbin
  #    /var/lib
  #    /var/lib/rsyslog
  #    /var/run
  #    /dev
  #    /entrypoint.sh
  #    /sys
  #    /tmp
  #    /lib/ld-musl-aarch64.so.1
  #    /proc
  #    /etc/mtab
  #    /etc/group
  #    /etc/resolv.conf
  #    /etc/rsyslog.conf
  #    /etc/hostname
  #    /etc/hosts
  #    /etc/passwd
  #    /run
  #    /usr/bin/busybox
  #    /usr/bin/sh
  #    /usr/sbin
  #    /usr/sbin/rsyslogd
  #    /usr/lib
  #    /usr/lib/libfastjson.so.4.3.0
  #    /usr/lib/libuuid.so.1
  #    /usr/lib/libuuid.so.1.3.0
  #    /usr/lib/libestr.so.0.0.0
  #    /usr/lib/libfastjson.so.4
  #    /usr/lib/libz.so.1
  #    /usr/lib/rsyslog
  #    /usr/lib/rsyslog/immark.so
  #    /usr/lib/rsyslog/lmzlibw.so
  #    /usr/lib/rsyslog/omprog.so
  #    /usr/lib/rsyslog/imklog.so
  #    /usr/lib/rsyslog/fmhash.so
  #    /usr/lib/rsyslog/lmtcpsrv.so
  #    /usr/lib/rsyslog/mmleefparse.so
  #    /usr/lib/rsyslog/omstdout.so
  #    /usr/lib/rsyslog/lmnetstrms.so
  #    /usr/lib/rsyslog/ommail.so
  #    /usr/lib/rsyslog/lmregexp.so
  #    /usr/lib/rsyslog/lmtcpclt.so
  #    /usr/lib/rsyslog/lmnet.so
  #    /usr/lib/rsyslog/imtcp.so
  #    /usr/lib/rsyslog/impstats.so
  #    /usr/lib/rsyslog/lmnsd_ptcp.so
  #    /usr/lib/rsyslog/imudp.so
  #    /usr/lib/rsyslog/imfile.so
  #    /usr/lib/rsyslog/mmexternal.so
  #    /usr/lib/rsyslog/imuxsock.so
  #    /usr/lib/rsyslog/imptcp.so
  #    /usr/lib/libestr.so.0
  #    /usr/lib/libz.so.1.3.2

# use alpine install rsyslog

FROM alpine:3.23 AS donor

ADD lib/img-mangler/alpine-mk-pkg-tarball.sh /
RUN  set -eux ;\
  umask 022 ;\
  apk add rsyslog ;\
  sh /alpine-mk-pkg-tarball.sh rsyslog / ;\
  mkdir -p /scratch/usr/bin /scratch/usr/etc /scratch/var/lib/rsyslog ;\
: # EO RUN

# create new rootfs /scratch
#   extract relevant files
#     bin
#     lib
#     /bin/sh via busybox, delete for shellcode sandbox ;)

COPY images/app-rsyslog-pure.Dockerfile.d/entrypoint.sh /scratch/entrypoint.sh

RUN  set -eux ;\
  cd /scratch ;\
  mkdir tmp ;\
  chmod 177 tmp ;\
  chmod 0755 /scratch/entrypoint.sh ;\
  ln -s usr/bin bin ;\
  ln -s bin sbin ;\
  ln -s bin /usr/sbin ;\
  ln -s tmp run ;\
  ln -s /run var/run ;\
  tar xzf /rsyslog.pkg.tar.gz -C /scratch ;\
  rm -rf etc/logrotate.d etc/rsyslog* usr/etc ;\
  cp -a /bin/busybox /scratch/bin/busybox ;\
  grep -E "^(root|adm)" /etc/passwd > /scratch/etc/passwd ;\
  grep -E "^(root|adm)" /etc/group > /scratch/etc/group ;\
  ln -s busybox /scratch/bin/sh ;\
: # EO RUN

COPY images/app-rsyslog-pure.Dockerfile.d/rsyslog.conf /scratch/etc/rsyslog.conf

# copy prepared rootfs to empty container

FROM scratch

COPY --from=donor /scratch /

ENTRYPOINT [ "/entrypoint.sh" ]
