# (C) 2024 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# set base, copy scripts & out-of-tree resources
FROM sbc:rpi64-rpios-full

# copy 64bit scripts to own snippet directory
COPY images/rpi64-rpios-lite-ci.Dockerfile.d /src/images/rpi64-rpios-lite-ci.Dockerfile.d/
