# (C) 2024-2025 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# set base, copy scripts & out-of-tree resources
FROM sbc:x6100-r1cbu-v0.28.0-opt-alpine

# a bit of code reuse
COPY       x6100-v1.1.9-mod.Dockerfile.d/  /src/x6100-v1.1.9-mod.Dockerfile.d/

# run scripts that do the modifications steps in one layer
# * moving files around - see # copy scripts & outoftree resources above
# * adding stuff, etc
