# example dnsmasq.conf
#

bind-interfaces

resolv-file=/etc/resolv.conf
#server=10.53.53.53
#server=fd53::53

interface=V1000
dhcp-range=10.67.69.100,10.67.69.200,255.255.255.0,12h

enable-tftp
tftp-root=/tftp

dhcp-option=option:router,0.0.0.0
dhcp-option=option:dns-server,0.0.0.0

# handy tags for identifiying multiple hardware types
# BIOS
dhcp-match=set:x86PC,option:client-arch,0
dhcp-boot=tag:x86PC,/grub/i386-pci/core.0,0.0.0.0
# UEFI AMD64
dhcp-match=set:X86-64_EFI,option:client-arch,7
dhcp-match=set:X86-64_EFI,option:client-arch,9
dhcp-boot=tag:X86-64_EFI,/grub/x86_64-efi/core.efi,0.0.0.0
# UEFI ARM64
dhcp-match=set:ARM64_EFI,option:client-arch,11
dhcp-boot=tag:ARM64_EFI,/grub/arm64-efi/core.efi,0.0.0.0
# Bluefield
dhcp-vendorclass=set:NVIDIA-BF-PXE,NVIDIA/BF/PXE
