# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE

FROM sbc:armhf-Alpine-3.21 AS alpine
FROM sbc:turingpi2

# keep imported build /vanilla rom with original bmcd and tpi
RUN mv /target /vanilla

# start /target with fresh armhf alpine
COPY --from=alpine /target/ /target

# populate modules from vanilla
RUN cp -a /vanilla/lib/modules /target/lib/modules
