# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE

# build turing pi image to get rootfs
output/turingpi2-alpine.img: output/turingpi2-alpine.rootfs.tar.zst bpi2m0-alpine.Dockerfile.d/docker-to-sd-card-img.sh
	$(E) "GENIMAGE $(NAME_PFX)$(NAME):$(patsubst output/%,%,$(@:.img=))"
	$(Q) mkdir -p output
	$(Q) ./bin/img-mangler -p --image $(NAME_PFX)$(NAME):$(patsubst output/%,%,$(@:.img=)) sh $(SHOPT) bpi2m0-alpine.Dockerfile.d/docker-to-sd-card-img.sh $< $@
