#!/bin/sh
# (C) 2023-2025 Joerg Jungermann, GPLv2 see LICENSE
set -e -u

DOCKERFILE="$1"
SEEDFILE="$2"
SEEDDIR="${2%/*}"
MODE="singlestep"

# redirect to STDOUT if run with - as output
[ "${1:--}" = "-" ] || \
  exec > "$1"

# try to generate less layers
# Pro:
#  * speed up builds on qemu emulated environments
# Cons:
#  * looses docker cache for build layers
#
if grep "meta: onestep" "$SEEDFILE" > /dev/null; then
  MODE="onestep"
fi

recipe_list() {
  awk '$1 == "RECIPE" {print $2}' "$SEEDFILE"
}

recipe_list_dirs() {
  awk '$1 == "RECIPE" { print "recipes/" $2 }' "$SEEDFILE"
}

recipe_RECIPE_transform() {
  awk '$1 != "RECIPE"' < "$SEEDFILE"
  [ "$MODE" != onestep ] || \
    recipe_list | (
      dirs=
      while read recipe; do
        echo "# RECIPE $recipe"
        path="recipes/$recipe"
        if [ -d "$path" ]; then
          dirs="$dirs $path"
        else
          echo "E: this should not happen." >&2
          exit 1
        fi
      done
      if [ -n "$dirs" ]; then
        echo "COPY $dirs /src/${SEEDDIR}/"
      fi
    )
}

cat <<EOF
#---- BEGIN "$SEEDFILE"
$( recipe_RECIPE_transform )
ENV SRC=/src/$SEEDDIR
#---- END "$SEEDFILE"

#---- AUTO GENERATED by $0 - mode: $MODE
EOF

recipe_list_sorted_snippets() {
  local pwd="$PWD"
  ( recipe_list_dirs
    echo "$SEEDDIR"
  ) | \
    while read path; do
      cd "$pwd"
      cd "$path"
      find . -maxdepth 1 -type f -name "[0-9][0-9][0-9]_*"
    done | \
      sort -u
}

onestep() {
  echo "COPY ${SEEDDIR} /src/${SEEDDIR}/"

  echo 'RUN set -eu ;\'
  recipe_list_sorted_snippets | \
    while read i; do
      echo '    /bin/sh -eu '"/src/$SEEDDIR/${i#./}"' ;\'
    done
  echo ': # eo RUN'
}

singlestep() {
  local dirs_added=" "
  recipe_list_sorted_snippets | \
    ( while read file; do
        file="${file#./}"
        for dir in $( recipe_list_dirs ; echo "$SEEDDIR" ); do
          dir="$dir"
          case "$dirs_added" in
            *" $dir "* ) ;;
            * )
             i="$dir/lib.sh"
             [ ! -f "$i" ] || \
               echo "COPY $i /src/$i"
             dirs_added="$dirs_added $dir "
            ;;
          esac
          i="${dir}/${file}"
          [ ! -L "$i" ] && [ ! -f "$i" ] || \
             echo "COPY $i /src/$SEEDDIR/${file#*/}"
          [ ! -L "$i.d" ] && [ ! -d "$i.d" ] || \
            echo "COPY $i.d/ /src/$SEEDDIR/${file#*/}.d"
        done
        echo "RUN exec /bin/sh -eu /src/$SEEDDIR/${file#*/}"
      done
    )
}

case "$MODE" in
  onestep | singlestep ) $MODE ;;
  * )
    echo "$0: ERROR, this should not happen."
    exit 2
    ;;
esac
