# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE

FROM sbc:turingpi2-alpine

COPY input/artifacts/turingpi2-alpine-rkdevelop.tar.zst /
COPY input/artifacts/turingpi2-alpine-rpiboot.tar.zst /

RECIPE alpine/keepalived
