#!/bin/sh
# (C) 2023 Joerg Jungermann, GPLv2 see LICENSE
set -e -u

DOCKERFILE="$1"
SEEDFILE="$2"
SEEDDIR="${2%/*}"
MODE="singlestep"

# try to generate only one layer
# Pro:
#  * speed up builds on qemu emulated environments
# Cons:
#  * looses docker cache for build layers
#

if grep "meta: onestep" "$SEEDFILE" > /dev/null; then
  MODE="onestep"
fi

exec > "$1"
cat <<EOF
#---- AUTO GENERATED by $0 - mode: $MODE

#---- BEGIN "$SEEDFILE"
$(cat "$SEEDFILE")
#---- END "$SEEDFILE"

#---- auto generated section by $0 - mode: $MODE
COPY ${SEEDDIR} /src/${SEEDDIR}/
ENV SRC=/src/$SEEDDIR
EOF

case "$MODE" in
  onestep )
    echo 'RUN set -eu ;\'
    for i in "$SEEDDIR"/[0-9][0-9][0-9]_*; do
      [ -f "$i" ] || \
        continue
    echo '    /bin/sh -eu '"/src/${i#/}"' ;\'
    done
    echo ': # eo RUN'
    ;;
  singlestep )
    for i in "$SEEDDIR"/[0-9][0-9][0-9]_*; do
      [ -f "$i" ] || \
        continue
    
        echo ""
        echo "#- $i"
        echo "RUN exec /bin/sh -eu /src/${i#/}"
    done
    ;;
  * )
    echo "$0: ERROR, this should not happen."
    exit 2
    ;;
esac
