# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE

output/rpi-alpin%.img: output/rpi-alpin%.rootfs.tar.zst rpi-alpine.Dockerfile.d/docker-to-sd-card-img.sh
	$(E) "GENIMAGE $(NAME_PFX)$(NAME):$(patsubst output/%,%,$(@:.img=))"
	$(Q) mkdir -p output
	$(Q) ./bin/img-mangler -p --image $(NAME_PFX)$(NAME):$(patsubst output/%,%,$(@:.img=)) sh $(SHOPT) rpi-alpine.Dockerfile.d/docker-to-sd-card-img.sh $< $@

