#!/bin/sh
#- config
#- pedantic thumb-screws
  set -eu

#- debugging, if needed
  PS4="${0}[$$]: +"
  #set -x

#- settings
  OVERLAY=${1:-/overlay}
  FILTER=${2:-LABEL=mmc-data}
  LABEL="${FILTER#LABEL=}"

log() {
  echo "OVERLAY: $*"
}

die() {
  rs=$1
  shift
  log $*
  exit $rs
}

if mountpoint $OVERLAY > /dev/null 2>&1; then
  log "$0: there is something mounted at $OVERLAY, ABORT"
  exit 1
fi

log "searching for overlay and data partition..."
for try in : "die 69 error creating data/overlay partition"; do
  DEVNAME=
  TYPE=
  eval "$(blkid -t $FILTER -o export || :)" || :
  if [ -n "${DEVNAME:-}" ]; then
    break # found partition
  else
    log "no data partition found with filter: $FILTER"
    # assumptions:
    #  * freshly burned image
    #  * ==> booted from ...
    #  * ==> RO partition is
    P_ROOT="$(findmnt -o SOURCE -n /)"
    BLK="${P_ROOT%[0-9]}"
    N="${P_ROOT#$BLK}"
    N=$(( N + 1 ))
    P_DATA="$BLK$N"
    #  * ==> new partition will be created at the end of SD card named
    echo ",,," | sfdisk -a ${BLK%p} --force
    partx -u ${BLK%p}
    mkfs.f2fs -l $LABEL $P_DATA -f
  fi
  $try
done

log "found $DEVNAME"
mount -t $TYPE "$DEVNAME" "$OVERLAY"

# use subdirectory to allow fresh bootstrapping by renaming or deleting
# /overlay on data partition
# maintainign multiple environements using symlinks and dirs does also work
if [ ! -d "$OVERLAY/overlay" ]; then
  mkdir -p "$OVERLAY/overlay"
  log "$DEVNAME:$OVERLAY - create fresh overlay"
fi
log "using overlay $DEVNAME:$OVERLAY"
mount -o bind "$OVERLAY/overlay/." "$OVERLAY"
