# (C) 2024 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

FROM sbc:bpi2m0-Armbian-25.02-bookworm-minimal

CMD \
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  exec env HOME=/root SHELL=/bin/bash chroot /target /bin/bash -l ;\
: # eo CMD
