# (C) 2023 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

FROM bpi2m0:Armbian-24.05-Bookworm-CLI

CMD \
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  exec env HOME=/root SHELL=/bin/bash chroot /target /bin/bash -l ;\
: # eo CMD
