# (C) 2025 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

FROM sbc:rpi-rpios-lite AS rpios
FROM sbc:bpi2m0-alpine

RUN set -eu ;\
  rm -rf /vanilla /target/boot /target/lib/modules /target/lib/firmware

# populate modules and boot from armbian
COPY --from=rpios /target/boot /target/boot
COPY --from=rpios /target/lib/modules /target/lib/modules
COPY --from=rpios /target/lib/firmware /target/lib/firmware
