#!/bin/sh
[ -n "$VERBOSE" ] && set -x

[ "${IF_LINK_TYPE}" = "bridge" ] || [ -n "$IF_BRIDGE_PORTS" ] || return 0 # no bridge

case "$PHASE" in
  create)
    if [ -d "/sys/class/net/${IFACE}" ]; then
      iface_type=$(ip -d link show dev "${IFACE}" | head -n3 | tail -n1 | awk '{ print $1 }')
      if [ "${iface_type}" != 'bridge' ]; then
        echo "Interface ${IFACE} exists but is of type ${iface_type} instead of dummy"
        exit 1
      fi
      exit 0
    fi
    ${MOCK} ip link add "${IFACE}" type bridge
    ;;
  destroy)
    if [ -z "${MOCK}" -a ! -d "/sys/class/net/${IFACE}" ]; then
      exit 0
    fi
    ${MOCK} ip link del "${IFACE}"
    ;;
  pre-up)
    if [ ! "$IF_BRIDGE_PORTS" = none ]; then
      for dev in $IF_BRIDGE_PORTS; do
      ip -4 addr flush $dev
      ip -6 addr flush $dev
      echo 1 > /proc/sys/net/ipv6/conf/$dev/disable_ipv6
    done
    fi
    ;;
  * )
    set -x
    env | sort
    ;;
esac
