# extlinux.conf for L4TLoader

TIMEOUT 30
DEFAULT 6.8.12-1021-tegra

MENU TITLE L4T boot options

LABEL 6.8.12-1021-tegra
  MENU LABEL 6.8.12-1021-tegra
  LINUX  /boot/vmlinuz-6.8.12-1021-tegra
  INITRD /boot/initrd.img-6.8.12-1021-tegra

  # Orin NX 16GB - no DTB overlay on a Nvidia/WaveShare/RK1 carrier board
  FDT    /boot/dtb/tegra234-p3768-0000+p3767-0000-nv-super.dtb
  APPEND ${cbootargs} root=UUID= rootflags= console=ttyTCU0,115200 mminit_loglevel=4 firmware_class.path=/etc/firmware fbcon=map:0 video=efifb:off console=tty0 efi_pstore.pstore_disable=1 pstore.backend=ramoops efi=runtime pci=pcie_bus_perf nvme.use_threaded_interrupts=1 swiotlb=2048

  #OVERLAYS /boot/overlay-user/EXAMPLE.dtbo
