output/amd64-EFI-CI-%.img: .deps/amd64-EFI-CI-%.built amd64-EFI-CI-bookworm.Dockerfile.d/generate-image.sh
	$(E) "IMG $@"
	$(Q) mkdir -p output ;\
		   ./bin/img-mangler -p --image $(NAME_PFX)$(NAME):$(patsubst output/%,%,$(@:.img=)) sh $(SHOPT) /src/amd64-EFI-CI-bookworm.Dockerfile.d/generate-image.sh $@

