# (C) 2023 Joerg Jungermann, GPLv2 see LICENSE

FROM bpi2m0:alpine-base

CMD \
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  exec env HOME=/root SHELL=/bin/bash chroot /target /bin/bash -l ;\
: # eo CMD
