# (C) 2026 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

FROM sbc:NVidia-Tegra-Jetson-Linux-39.2.1.BSP AS drivers
FROM sbc:NVidia-Tegra-Jetson-Linux-39.2.1.rootfs

COPY --from=drivers /target/Linux_for_Tegra/ /Linux_for_Tegra/
