# (C) 2026 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# import fresh arm64 alpine for the initramfs add busybox.static
FROM sbc:armhf-Alpine-3.24 AS busybox-static
RUN set -eu ;\
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  chroot /target apk add busybox-static

FROM sbc:armhf-OptAlpine-3.24 AS alpine
COPY --from=busybox-static /target/bin/busybox.static /sbin/busybox.static

FROM sbc:NVidia-Tegra-Jetson-Linux-39.2.1.BSP AS drivers
FROM sbc:NVidia-Tegra-Jetson-Linux-39.2.1.rootfs

COPY --from=drivers /target/Linux_for_Tegra/ /Linux_for_Tegra/

COPY --from=alpine  / /OptAlpine

RECIPE armbian/etckeeper
