#!/bin/sh
set -eu
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

DEBUG=
if [ -n "$DEBUG" ]; then
  exec 1>> /run/${0##*/}.log
  exec 2>&1
  echo
  echo "--- $(date)"
  echo "'$0' '$1' '$2' '$3'"
  set -x
fi

if [ "$#" != 3 ]; then
  echo "E: wrong number of arguments" >&2
  exit 1
fi

NORMAL_DIR="${1}"
EARLY_DIR="$2"
LATE_DIR="$3"


SHADOW_LOCATION=/run/volatile-fs
DIRS=

if [ -r /etc/default/volatile-fs ]; then
  . /etc/default/volatile-fs
fi

[ -n "$DIRS" ] ||
  return 0

mkdir -p "$SHADOW_LOCATION"
chmod 700 "$SHADOW_LOCATION"

# TODO:
#  * add systemd.mount in local-fs.target.wants (see https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdBindMountUnits)
for d in $DIRS; do
  if ! [ -d "$d" ]; then
    echo "W: '$d' does not exist, skip" >&2
    continue
  fi

  DST="$SHADOW_LOCATION/$d"
  # when we have been reloaded do not recreate and preseed existing directories
  if ! [ -d "$DST" ]; then
    mkdir -p "${DST%/*}"
    cp -a "$d" "$DST"
  fi
  if ! mountpoint "$d" 2> /dev/null 1>&2; then
    mount -o bind "$DST" "$d"
    echo "I: shadowed '$d'"
  fi
done

# vim: ft=sh sw=2 ts=2 et foldmethod=marker foldmarker={\ #,}\ #
