# (C) 2025-26 Joerg Jungermann, GPLv2 see LICENSE
# meta: #onestep

# import fresh arm64 alpine for the initramfs add busybox.static
FROM sbc:aarch64-Alpine-3.23 AS busybox-static
RUN set -eu ;\
  rm -f /target/etc/resolv.conf ;\
  cp /etc/resolv.conf /target/etc/resolv.conf ;\
  chroot /target apk add busybox-static
FROM sbc:aarch64-Alpine-3.23 AS alpine
COPY --from=busybox-static /target/bin/busybox.static /target/sbin/busybox.static

FROM sbc:bluefield-doca-lts
COPY --from=alpine /target /initrd.alpine
