# /etc/rsyslog.conf

## INPUT
module(load="imuxsock") # provides support for local system logging
module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

## OUTPUT

# log to STDOUT (when started with -n)
*.* -/proc/self/fd/1

# log in uniefed RFC compotible and rsyslog compatible format
#  * set proper environment set IP in $UNIFIED_RSYSLOG_REMOTE
#action(type="omfwd" protocol="tcp" target="$UNIFIED_RSYSLOG_REMOTE" port="514" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on")
