# (C) 2023 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

# set base, copy scripts & out-of-tree resources
FROM bpi2m0:armbian-bookworm-vanilla

#-
# run scripts that do the modifications steps in one layer
# * moving files around - see # copy scripts & outoftree resources above
# * adding stuff, etc
#-
