#!/bin/sh
set -e

update_rc() {
  SRC="$__PREFIX__/etc/init.d"
  TARGET="$__PREFIX__/usr/local/sbin"

  for initfile in "$SRC"/*; do
    file="${initfile##*/}"
    rcfile="${TARGET}/rc${file}"

    if [ -x "$initfile" -a ! -d "$initfile" ]; then
      if [ ! -e "$rcfile" ]; then
        echo -n "${initfile#$__PREFIX__} -> ${rcfile#$__PREFIX__} "
        ln -sf "$0" "$rcfile" && echo Ok. || echo "failed."
      fi
    fi
  done

  if [ -z "$__PREFIX__" ]; then
    for rcfile in $TARGET/rc*; do
      link="$(readlink "$rcfile")"
      case "$link" in
        "$SRC"* ) : ;;
        * ) continue ;;
      esac
      file="$(basename "$rcfile")"
      file="${file#??}"
      initfile="$SRC/$file"

      if [ -L "$rcfile" ]; then
        if [ ! -x "$initfile" -o -d "$initfile" ]; then
          echo -n "removed old $rcfile "
          rm -f "$rcfile" && echo Ok. || echo "failed."
        fi
      fi
    done
  fi
}

rc_call() {
  set -x
  svc="${1##*/rc}"
  if [ "$1" = "$svc" ]; then
    echo "${1##*/}: could not resolve service, ABORT"
    exit 1
  fi
  shift
  if [ -x "/etc/init.d/$svc" ]; then
     exec "/etc/init.d/$svc" "$@"
  else
    echo "${0##*/}: /etc/init.d/$svc is not an executable, ABORT"
    exit 1
  fi
}

case "$0" in
  */update-rc ) update_rc ;;
   */sbin/rc* ) rc_call "${0}" "$@" ;;
   * )
      echo "${0##*/}: unknown call '$0'"
      exit 1
   ;;
esac

# vim: ts=2 sw=2 et ft=sh
