# (C) 2024 Joerg Jungermann, GPLv2 see LICENSE
# meta: onestep

# set base, copy scripts & out-of-tree resources
FROM sbc:x6100-v1.1.9-opt-alpine

# run scripts that do the modifications steps in one layer
# * moving files around - see # copy scripts & outoftree resources above
# * adding stuff, etc
