# (C) 2023 Joerg Jungermann, GPLv2 see LICENSE

FROM bpi2m0:alpine-base AS alpine
RUN tar cf /alpine.rootfs.tar.zst -I zstd -C /target --xattrs --acl .

# set base, copy scripts & out-of-tree resources
FROM bpi2m0:armbian-bookworm-base

COPY --from=alpine /alpine.rootfs.tar.zst /target/opt

#-
# run scripts that do the modifications steps in one layer
# * moving files around - see # copy scripts & outoftree resources above
# * adding stuff, etc
#-
